/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Application;
import Model.vitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author asequ
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    private Application application;
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldObservationId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addObservationBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Create a vital sign ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 180, 20));

        fieldObservationId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationIdActionPerformed(evt);
            }
        });
        add(fieldObservationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 20, 20));

        jLabel3.setText("Blood Pressure");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 20));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 30));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 30));

        jLabel4.setText("Temperature");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        addObservationBtn.setText("ADD OBSERVATION");
        addObservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservationBtnActionPerformed(evt);
            }
        });
        add(addObservationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservationBtnActionPerformed
        // TODO add your handling code here:
        //add an observation to vital sign history
        vitalSignHistory history = this.application.getHistory();
        String id = fieldObservationId.getText();
        String temperature = fieldTemperature.getText();
        String bloodPressure = fieldBloodPressure.getText();
        history.createObservation(Integer.valueOf(id), Double.valueOf(temperature), Double.valueOf(bloodPressure));
        JOptionPane.showMessageDialog(null, "Added Observation");
    }//GEN-LAST:event_addObservationBtnActionPerformed

    private void fieldObservationIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObservationBtn;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationId;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
