/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea Joyce Sequeira
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private DeliveryPackage delPackage;
    private Boolean validate = false;
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        // logic to take information from the user and store it in the delivery package
        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        packageWeight = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        packageId = new javax.swing.JTextField();
        customerId = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        productPrice = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        productId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveProductButton = new javax.swing.JButton();

        jTextField3.setText("jTextField1");

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Package ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 41, 70, 20));

        jLabel2.setText("Customer Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 41, -1, 30));

        jLabel3.setText("Weight");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 96, 55, 23));

        jLabel4.setText("ID");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 96, 55, 23));

        packageWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightActionPerformed(evt);
            }
        });
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 89, 97, 37));

        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 34, 97, 37));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 34, 97, 37));

        customerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdActionPerformed(evt);
            }
        });
        add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 89, 97, 37));

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 157, -1, -1));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 279, 97, 28));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 245, 97, 28));
        add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 207, 97, 28));

        jLabel5.setText("Product Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 214, -1, -1));

        jLabel6.setText("Product Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 252, -1, -1));

        jLabel7.setText("Product Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 294, -1, -1));

        saveProductButton.setText("SAVE PRODUCT");
        saveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductButtonActionPerformed(evt);
            }
        });
        add(saveProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 325, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void customerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdActionPerformed

    private void saveProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductButtonActionPerformed
        // TODO add your handling code here:
        String prodId = productId.getText();
        String prodName = productName.getText();
        String prodPrice = productPrice.getText();
        Product product = this.delPackage.createProduct(Integer.valueOf(prodId), prodName, Double.valueOf(prodPrice));
        JOptionPane.showMessageDialog(null, "Added Product");
        
    }//GEN-LAST:event_saveProductButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String id = packageId.getText();
        String weight = packageWeight.getText();
        String custName = customerName.getText();
        String custId = customerId.getText();
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(custId));
        customer.setFullName(custName);
        if(validate) {
            JOptionPane.showMessageDialog(null, "Please fill all the values");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void packageWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightActionPerformed
 private void custName1FocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        
        System.out.println(customerName.getText() + " -- the customer name");
        String name = customerName.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerId;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveProductButton;
    // End of variables declaration//GEN-END:variables
}
