/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author Nidhi Raghavendra
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Person person;
    
    public MainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CreateJPanel = new javax.swing.JPanel();
        fieldName = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        officePhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        permStreet1 = new javax.swing.JTextField();
        localPhone1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        officeEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        personalEmail1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ViewJPanel = new javax.swing.JPanel();
        viewName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewPermAddre = new javax.swing.JLabel();
        viewPersonalPhone = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewPersonalEmail = new javax.swing.JLabel();
        viewOffieEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateJPanel.setBackground(new java.awt.Color(204, 204, 255));
        CreateJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CreateJPanel.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 124, 37));
        CreateJPanel.add(fieldStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 239, 124, 36));

        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        CreateJPanel.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jLabel3.setText("Name");
        CreateJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 20));

        jLabel4.setText("Permanent street");
        CreateJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        CreateJPanel.add(officePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, 31));

        jLabel5.setText("Street");
        CreateJPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 250, -1, -1));
        CreateJPanel.add(permStreet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 293, 130, 31));
        CreateJPanel.add(localPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 130, 31));

        jLabel6.setText("Office Phone");
        CreateJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setText("Personal Phone");
        CreateJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        CreateJPanel.add(officeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 130, 31));

        jLabel8.setText("Office Email");
        CreateJPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));
        CreateJPanel.add(personalEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, 31));

        jLabel9.setText("Personal Email");
        CreateJPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jSplitPane1.setLeftComponent(CreateJPanel);

        ViewJPanel.setBackground(new java.awt.Color(255, 204, 204));
        ViewJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewName.setText("jLabel3");
        ViewJPanel.add(viewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        viewStreet.setText("jLabel3");
        ViewJPanel.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        viewPermAddre.setText("jLabel10");
        ViewJPanel.add(viewPermAddre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        viewPersonalPhone.setText("jLabel1");
        ViewJPanel.add(viewPersonalPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        viewOfficePhone.setText("jLabel1");
        ViewJPanel.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        viewPersonalEmail.setText("jLabel1");
        ViewJPanel.add(viewPersonalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        viewOffieEmail.setText("jLabel1");
        ViewJPanel.add(viewOffieEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jSplitPane1.setRightComponent(ViewJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String name = fieldName.getText();
        String street = fieldStreet.getText();
        String permStreet = permStreet1.getText();
        long localPhone = Long.valueOf(localPhone1.getText());
        long offPhone = Long.valueOf(officePhone.getText());
        String personalEmail = personalEmail1.getText();
        String offEmail = officeEmail.getText();
        
        this.person.setName(name);
        //Person obj2 = new Person();
        
        Address address = this.person.getAddress();
        address.setStreet(street);
        
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreet(permStreet);
        
        Contact officeContact = this.person.getOfficeContact();
        officeContact.setPhoneNumber(offPhone);
        officeContact.setEmailID(offEmail);
        
        Contact locatContact = this.person.getPersonalContact();
        locatContact.setPhoneNumber(localPhone);
        locatContact.setEmailID(personalEmail);
        
        display();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void display() {
        viewName.setText(this.person.getName());
        viewStreet.setText(this.person.getAddress().getStreet());
        viewPermAddre.setText(this.person.getPermanentAddress().getStreet());
        
        viewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        viewOfficePhone.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        
        viewPersonalEmail.setText(this.person.getPersonalContact().getEmailID());
        viewOffieEmail.setText(this.person.getOfficeContact().getEmailID());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateJPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JPanel ViewJPanel;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField localPhone1;
    private javax.swing.JTextField officeEmail;
    private javax.swing.JTextField officePhone;
    private javax.swing.JTextField permStreet1;
    private javax.swing.JTextField personalEmail1;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewOffieEmail;
    private javax.swing.JLabel viewPermAddre;
    private javax.swing.JLabel viewPersonalEmail;
    private javax.swing.JLabel viewPersonalPhone;
    private javax.swing.JLabel viewStreet;
    // End of variables declaration//GEN-END:variables
}
