/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author asequ
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form medicineJPanel
     */
    private Application application;
    
    public MedicineAssignJPanel() {
        initComponents();
    }

    MedicineAssignJPanel(Application application) {
        initComponents();
        this.application = application;
        populateDropDowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineBox = new javax.swing.JComboBox();
        observationBox = new javax.swing.JComboBox();
        assignButton = new javax.swing.JButton();
        displayValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 200, 40));

        observationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                observationBoxItemStateChanged(evt);
            }
        });
        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 200, 40));

        assignButton.setText("ASSIGN");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        add(assignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 80, 40));

        displayValue.setText("DISPLAY VALUES");
        add(displayValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        // TODO add your handling code here:
        Observation o = (Observation) observationBox.getSelectedItem();
        
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        o.setMedication(m);
    }//GEN-LAST:event_assignButtonActionPerformed

    private void observationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_observationBoxItemStateChanged
        // TODO add your handling code here:
        Observation o = (Observation)observationBox.getSelectedItem();
        if(o.getMedication()!= null)
        {
            displayValue.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_observationBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.JLabel displayValue;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    // End of variables declaration//GEN-END:variables

    public void populateDropDowns() {
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
         ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
         for(Observation o: observations){
             observationBox.addItem(o);
         }
           for(Medicine o: medicines){
             medicineBox.addItem(o);
         }
        
        
        
    }
}
